# -*- coding: utf-8 -*-
"""DVR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11N5BFE5-6Y-6KT-0w935Zw1mkCI-KJhq

DVR basis defined using sin-DVR. 
phi_k = sum_j U_{jk} phi_j, where U_{jk} = sqrt(omega_k) phi_j(x_k)
phi_j = sqrt(2 / L) sin(pi j x / L), and
omega_k = L / (n + 1)


Problem assumes two particles in a potential V. Working with relative coordinate. 
Working with reduced radial wave equation. Assuming l=0 (S wave, no centrifugal barrier).
"""

import numpy as np
from numpy import pi, exp, sqrt, sin
import scipy.linalg as sl
import matplotlib.pyplot as plt

class DVR:
  mu, hbar, N = 1/2, 1.0, 2

  def __init__(self, n, L, rotation_angle=0, potential=None):
    self.r, self.w = DVR.get_mesh(n, L)
    self.n = n
    self.L = L
    self.rotation_angle = rotation_angle

    self.potential = potential

    self.rr = None

    # construct Hamiltonian
    self.H0 = self.construct_H0(n, L)
    self.V = self.calculate_potential(potential)
    self.H = self.H0 + self.V

  def get_mesh(n, L):
    # working w/ reduced radial, so [0, L], and use sine
    krange = np.arange(1, n+1)
    r = krange * L / (n+1)
    w = L / (n + 1)
    return r, w

  def calculate_potential(self, potential):
    if potential is None:
      return 0
    if self.rotation_angle != 0:
      phase = exp(self.rotation_angle * 1j)
      r = self.r * phase
    else:
      r = self.r
    V = np.diag(potential(r))
    return V

  def construct_H0(self, n, L):
    T = np.zeros((n, n), dtype=np.complex128)

    for k in range(n):
      for l in range(n):
        kp  = k + 1
        lp = l + 1
        if k == l:
          T[k, l] = (2*(n+1)**2+1)/3 - 1/sin(pi*kp/(n+1))**2
        else:
          T[k, l] = (-1)**(kp-lp) * ( 1/sin(pi*(kp-lp)/(2*(n+1)))**2 - 1/sin(pi*(kp+lp)/(2*(n+1)))**2 )

    coeff = self.hbar**2/(2*self.mu) * pi**2/(2*self.L**2)
    T *= coeff

    if self.rotation_angle != 0:
      phase = exp(-self.rotation_angle * 2j)
      T *= phase

    return T

  def reset_rotation_angle(self, rotation_angle):
    self.rotation_angle = rotation_angle
    self.H0 = self.construct_H0(self.n, self.L)
    self.V = self.calculate_potential(self.potential)
    self.H = self.H0 + self.V

  def compute_r2(self, state, rotate_rr=False, regulator=False):
    # radius is defined as 1/4<r^2> (due to CM)
    # not factoring in the overall $\int d\Omega (Y^0_0)^2$ factor.
    # c-normalize state
    state = state / sqrt(np.sum(state**2))
    rs = self.r
    if regulator:
        alpha = 0.1
        rs = rs * exp(-alpha * rs)
    if rotate_rr:
        expect_rr = 0.25 * np.sum(state**2 * rs**2) * exp(2j*self.rotation_angle)
    else:
        expect_rr = 0.25 * np.sum(state**2 * rs**2)
    return expect_rr

  def eig(self):
    eigvals, eigvecs = sl.eig(self.H)
    idx = np.argsort(np.abs(eigvals))
    eigvals, eigvecs = eigvals[idx], eigvecs[:, idx]
    return eigvals, eigvecs

  def closest_eig_pole(self):
    eigvals, eigvecs = self.eig()

    contour = np.abs(np.angle(eigvals) - (-2*self.rotation_angle)) < 0.05
    eigvals[contour] = np.nan
    closest_pole_idx = np.argsort(np.abs(eigvals))

    eigvals = eigvals[closest_pole_idx]
    eigvecs = eigvecs[:, closest_pole_idx]
    return eigvals, eigvecs

  def closest_to_resonance(self, resonance, k=1):
    eigvals, eigstates = self.eig()
    idx = np.argsort(np.abs(eigvals - resonance))[:k]
    eigval = eigvals[idx]
    eigstate = eigstates[:, idx]
    return eigval, eigstate

  def construct_wavefunc(self, state, x_plot):
      # c-product normalize just in case
      state = state / sqrt(np.sum(state**2))
      # psi = sum_k c_k psi_k
      # psi = sum_j (sum_k U_jk c_k) phi_j
      # psi = sum_j (U @ c)_j phi_j
      j = np.arange(1, self.n+1) # sine mode indices
      k = np.arange(1, self.n+1) # DVR point indices

      # build U: shape (n_modes, n_DVRpoints) = (n, n)
      U = sqrt(2.0/(self.n+1)) * sin(pi*np.outer(j, k)/(self.n+1))

      # compute a = U @ c (sine coefficients)
      a = U @ state

      # evaluate sin basis on x plot points, shape (n_xplot, n_modes) = (n_xplot, n)
      sin_basis = sqrt(2.0/self.L) * sin(pi*np.outer(x_plot, j)/self.L)

      psi = sin_basis @ a
      return psi
      
class ECSystem:
  def __init__(self, n, L, resonance_energy, potential):
    self.system = DVR(n, L, potential=potential)
    self.n = n
    self.L = L
    self.resonance_energy = resonance_energy

    self.training_eigvals = []
    self.training_eigvecs = []
    self.training_rrs = []
    self.clear_all()

  def train(self, rotation_angles, k=1):
    # sampling eigenvectors corresponding to specific resonance state for many phi
    for phi in rotation_angles:
      self.system.reset_rotation_angle(phi)
      eigval, eigstate = self.system.closest_to_resonance(self.resonance_energy, k)
      for i, val in enumerate(eigval):
        # EC not being trained directly on rr data, but computing rr
        # of training states for completeness
        rr = self.system.compute_r2(eigstate[:, i], rotate_rr=True, regulator=False)
        self.training_eigvals.append(val)
        self.training_eigvecs.append(eigstate[:, i])
        self.training_rrs.append(rr)

  def construct_basis(self, verbose=False, augment=None):
    # constructing EC basis with c-product
    if augment == 'conj':
        BA_vecs = [np.conj(vec) for vec in self.training_eigvecs]
        self.training_eigvecs.extend(BA_vecs)
    self.EC_basis = np.transpose(np.vstack(self.training_eigvecs))
    self.EC_basis_T = np.transpose(self.EC_basis)
    self.N_mat = self.EC_basis_T @ self.EC_basis

    # Tikhonov regularization (not the same as the back-rotation reg
    eps = 1.0e-8
    self.N_mat = self.N_mat + eps * np.eye(self.N_mat.shape[0])
    if np.linalg.cond(self.N_mat) > 10**6 and verbose:
      print(f"WARNING: N matrix nearly singular: {np.linalg.cond(self.N_mat)}.")

  def reconstruct_DVRstate_from_ECState(self, EC_state):
    state = EC_state @ np.array(self.training_eigvecs)
    # c-normalize though not strictly necessary because we do it later
    c_norm = np.sum(state**2)
    state = state / sqrt(c_norm)
    return state

  def predict(self, rotation_angles_predict, rotate_rr):
    """
    Computes <r^2> and E for resonance for rotation angles in rotation_angles_predict 

    Parameters
    ----------
    rotation_angles_predict : ndarray or array-like
        Array of rotation angles to compute <r^2> and E at.
    rotate_rr (optional): bool, default False
        Decided if r^2 operator should be complex-rotated (True) or not (False).
        
    Returns
    -------
    rrs : ndarray
        Array of <r^2> data.
    energies : ndarray
        Array of energy data.

    Notes
    -----
    EC can't uniquely determine which eigvec corresponds to the resonance as we adjust phi,
    so we forcefully find it by choosing the energy that best matches the known resonance freq.
    """
    energies, rrs = [], []
    for phi in rotation_angles_predict:
      self.system.reset_rotation_angle(phi)
      H_target = self.system.H
      H_proj = self.EC_basis_T @ H_target @ self.EC_basis
      eigvals, eigvecs = sl.eig(H_proj, b=self.N_mat)

      """
      # commenting out because using resonance energy to sort
      rrs = []
      for eigvec in eigvecs.T:
        dvr_state = self.reconstruct_DVRstate_from_ECState(eigvec)
        rr = self.system.compute_r2(dvr_state)
        rrs.append(rr)
      rrs = np.array(rrs)
      """

      # cannot uniquely determine which eigvec corresponds to
      # resonance when phi = 0, so we forcefully find it
      # (this is contrived but all we can do)
      energy_idx = np.nanargmin(np.abs(self.resonance_energy - eigvals))
      energies.append(eigvals[energy_idx])
      DVRstate = self.reconstruct_DVRstate_from_ECState(eigvecs[:, energy_idx])
      rr = self.system.compute_r2(DVRstate, rotate_rr=rotate_rr)
      rrs.append(rr)
    return energies, rrs

  def grab_wavefunc_from_prediction(self, rotation_angle_predict, x_plot):
    self.system.reset_rotation_angle(rotation_angle_predict)
    H_target = self.system.H
    H_proj = self.EC_basis_T @ H_target @ self.EC_basis
    eigvals, eigvecs = sl.eig(H_proj, b=self.N_mat)

    energy_idx = np.nanargmin(np.abs(self.resonance_energy - eigvals))
    DVRstate = self.reconstruct_DVRstate_from_ECState(eigvecs[:, energy_idx])
    wavefunc = self.system.construct_wavefunc(DVRstate, x_plot)
    return wavefunc

  def grab_density_from_prediction(self, rotation_angle_predict, x_plot, rotate_rr):
    if rotate_rr:
        x_plot = x_plot.astype(complex)
        x_plot = x_plot * exp(-1j*rotation_angle_predict)
        
    wavefunc = self.grab_wavefunc_from_prediction(rotation_angle_predict, x_plot)
    density = wavefunc**2

    if rotate_rr:
        density = density * exp(-1j*rotation_angle_predict)
    return density
    
  def clear_all(self):
    self.training_eigvals = []
    self.training_eigvecs = []
    self.training_rrs = []

class ECEnsemble:
  def __init__(self, n_ecsystems, n_DVR, L, resonance_energy, potential):
    self.n_ecsystems = n_ecsystems
    self.n = n_DVR
    self.L = L
    self.resonance_energy = resonance_energy

    self.models = [ECSystem(n_DVR, L, resonance_energy, potential) for _ in range(n_ecsystems)]
    self.clear_all()

  def clear_all(self):
    for model in self.models:
      model.clear_all()

  def train(self, phi_range, points, k=1):
    for model in self.models:
      phis = np.random.uniform(phi_range[0], phi_range[1], points)
      model.train(phis, k)

  def construct_bases(self, v=False, augment=None):
    for model in self.models:
      model.construct_basis(verbose=v, augment=augment)

  def extrapolate(self, phi_predict, rotate_rr):
    extrapolated_energies = []
    extrapolated_rr = []

    extrapolated_energies_err95 = []
    extrapolated_energies_err68 = []
    extrapolated_rr_err95 = []
    extrapolated_rr_err68 = []
    for phi in phi_predict:
      rr_sample = []
      energy_sample = []
      for model in self.models:
        energy, rr = model.predict([phi], rotate_rr=rotate_rr)
        rr_sample.append(rr[0])
        energy_sample.append(energy[0])
      rr_sample = np.array(rr_sample)
      energy_sample = np.array(energy_sample)

      rr_med = np.median(rr_sample.real) + np.median(rr_sample.imag)*1j
      energy_med = np.median(energy_sample.real) + np.median(energy_sample.imag)*1j
      extrapolated_energies.append(energy_med)
      extrapolated_rr.append(rr_med)

      err95_p = (np.percentile(rr_sample.real, 50+95.4/2) +
                 np.percentile(rr_sample.imag, 50+95.4/2)*1j) - rr_med
      err95_m = rr_med - (np.percentile(rr_sample.real, 50-95.4/2) +
                       np.percentile(rr_sample.imag, 50-95.4/2)*1j)
      err68_p = (np.percentile(rr_sample.real, 50+68.2/2) +
                 np.percentile(rr_sample.imag, 50+68.2/2)*1j) - rr_med
      err68_m = rr_med - (np.percentile(rr_sample.real, 50-68.2/2) +
                       np.percentile(rr_sample.imag, 50-68.2/2)*1j)
      extrapolated_rr_err95.append([err95_m, err95_p])
      extrapolated_rr_err68.append([err68_m, err68_p])
        
      err95_p = (np.percentile(energy_sample.real, 50+95.4/2) +
                 np.percentile(energy_sample.imag, 50+95.4/2)*1j) - energy_med
      err95_m = energy_med - (np.percentile(energy_sample.real, 50-95.4/2) +
                       np.percentile(energy_sample.imag, 50-95.4/2)*1j)
      err68_p = (np.percentile(energy_sample.real, 50+68.2/2) +
                 np.percentile(energy_sample.imag, 50+68.2/2)*1j) - energy_med
      err68_m = energy_med - (np.percentile(energy_sample.real, 50-68.2/2) +
                       np.percentile(energy_sample.imag, 50-68.2/2)*1j)
      extrapolated_energies_err95.append([err95_m, err95_p])
      extrapolated_energies_err68.append([err68_m, err68_p])

    extrapolated_rr_err95 = np.array(extrapolated_rr_err95).T
    extrapolated_rr_err68 = np.array(extrapolated_rr_err68).T
    extrapolated_energies_err95 = np.array(extrapolated_energies_err95).T
    extrapolated_energies_err68 = np.array(extrapolated_energies_err68).T
    return extrapolated_energies, extrapolated_rr, \
          extrapolated_rr_err95, extrapolated_rr_err68, \
          extrapolated_energies_err95, extrapolated_energies_err68
  
  def extrapolate_density(self, phi_predict, x_plot, rotate_rr):
      extrapolated_densities = []
      extrapolated_densities_err95 = []
      extrapolated_densities_err68 = []

      for phi in phi_predict:
        density_sample = []
        for model in self.models:
            density = model.grab_density_from_prediction(phi, x_plot, rotate_rr=rotate_rr)
            density_sample.append(density)
        density_sample_stack = np.stack(density_sample, axis=0)
        real_den, imag_den = np.real(density_sample_stack), np.imag(density_sample_stack)

        density_med = np.median(real_den, axis=0) + np.median(imag_den, axis=0)*1j
        extrapolated_densities.append(density_med)

        # compute error bounds for density
        err95_p = (np.percentile(real_den, 50+95.4/2, axis=0) + 
                   np.percentile(imag_den, 50+95.4/2, axis=0)*1j) - density_med
        err95_m = density_med - (np.percentile(real_den, 50-95.4/2, axis=0) + 
                                 np.percentile(imag_den, 50-95.4/2, axis=0)*1j)
        err68_p = (np.percentile(real_den, 50+68.2/2, axis=0) + 
                   np.percentile(imag_den, 50+68.2/2, axis=0)*1j) - density_med
        err68_m = density_med - (np.percentile(real_den, 50-68.2/2, axis=0) + 
                                 np.percentile(imag_den, 50-68.2/2, axis=0)*1j)

        extrapolated_densities_err95.append([err95_m, err95_p])
        extrapolated_densities_err68.append([err68_m, err68_p])

      extrapolated_densities = np.stack(extrapolated_densities, axis=0)
      extrapolated_densities_err95 = np.stack(extrapolated_densities_err95, axis=1)
      extrapolated_densities_err68 = np.stack(extrapolated_densities_err68, axis=1)
      return extrapolated_densities, extrapolated_densities_err95, extrapolated_densities_err68

class Tikhonov:
    def __init__(self, n, L, resonance_energy, potential, r0=1.0, N=512, xmax=8.0, kappa=4e-4):
        """
        Class for computing radial density using Tikhonov regularization
        n : int
            Number of DVR basis states.
        L : float
            System length.
        resonance_energy : cfloat
            Complex resonance energy.
        potential : func
            Potential of system.
        r0 : float
            Reference scale for Tikhonov. Default 1.0.
        N : int
            Number of grid points for Fourier transform in Tikhonov. Default 512.
        xmax : float
            Maximum length to integrate to in log-space of Fourier transform. Default 8.0.
        kappa : float
            Tikhonov cutoff parameter.
        """

        self.system = DVR(n, L, potential=potential)
        self.resonance_energy = resonance_energy
        self.L = L

        self.r0 = r0
        self.N = N
        self.kappa = kappa

        self.xmax = xmax
        self.xmin = -np.log(L / r0)
        self.x = np.linspace(self.xmin, self.xmax, N)

        self.r_log = r0 * exp(-self.x)

    def _compute_wavefunc2_on_logmesh(self, rotation_angle):
        # reset system to correct rotation angle
        self.system.reset_rotation_angle(rotation_angle)
        # grab CS resonance
        _, eigstate = self.system.closest_to_resonance(self.resonance_energy)
        eigstate = eigstate[:, 0] / sqrt(np.sum(eigstate[:, 0]**2)) # c-normalize just in case

        u_on_logmesh = self.system.construct_wavefunc(eigstate, self.r_log)
        f = (u_on_logmesh)**2

        return f

    def _compute_fft(self, func):
        # compute FFT
        # np.fft gives discrete FFT. Need dx / sqrt(2pi) to approx integral
        dx = self.x[1] - self.x[0]
        f_hat = np.fft.fft(func) * (dx / sqrt(2*pi))
        
        # compute frequency points
        xis = np.fft.fftfreq(self.N, d=dx) * 2*pi
        return xis, f_hat

    def _apply_Tikhonov(self, rotation_angle, xis, fftfunc):
        # apply Tikhonov and compute inverse FFT
        dxi = xis[1] - xis[0]

        tikhonov = 1.0 / (1.0 + self.kappa * exp(-2*rotation_angle*xis))
        # multiply by N bc numpy ifft has 1/N factor that numpy fft doesn't
        f_reg = np.fft.ifft(fftfunc * tikhonov * exp(-rotation_angle*xis)) * (self.N*dxi/sqrt(2*pi))
        return f_reg

    def compute_density(self, rotation_angle, backrotate=True, ang_factor=1.0):
        """
        Compute the radial density at a specific rotation angle using Tikhonov.
        If backrotate=True, radial density is computed for back-rotated resonance.
        ang_factor is the factor contributed by the angular integral.
        Default is 1.0 since it's just an overall factor.
        """
        func = self._compute_wavefunc2_on_logmesh(rotation_angle)
        xis, f_hat = self._compute_fft(func)
        f_reg = self._apply_Tikhonov(rotation_angle, xis, f_hat)

        if backrotate:
            factor = ang_factor * exp(2j*rotation_angle)
        else:
            factor = ang_factor * exp(-1j*rotation_angle)

        tikhonov_density = factor * f_reg

        return self.r_log, tikhonov_density















