# -*- coding: utf-8 -*-
"""
DVR.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11N5BFE5-6Y-6KT-0w935Zw1mkCI-KJhq

DVR basis defined using sin-DVR. 
chi_k = sum_j U_{jk} phi_j, where U_{jk} = sqrt(omega_k) phi_j(x_k)
phi_j = sqrt(2 / L) sin(pi j x / L), and
omega_k = L / (n + 1)

Problem assumes two particles in a potential V. Working with relative coordinate. 
Working with reduced radial wave equation.
"""

import numpy as np
from numpy import pi, exp, sqrt, sin

import scipy.linalg as sl
import scipy.interpolate as si

from typing import Callable

import logging
logger = logging.getLogger(__name__)

class DVRCore:
    def __init__(self, n: int, L: float):
        self.r, self.w = DVRCore.get_mesh(n, L)
        self.n = n
        self.L = L
        
        self.x_plot = np.linspace(0, L, int(L*10))

    # ------------------------------ CORE DVR SETUP ------------------------------
    @staticmethod
    def get_mesh(n: int, L: float) -> tuple[np.ndarray, float]:
        """ computes the DVR quadrature mesh (positions, weights) """
        # working w/ reduced radial, so [0, L], and use sine
        krange = np.arange(1, n+1)
        r = krange * L / (n+1)
        w = L / (n + 1)
        return r, w

    # --------------------------------------------- WAVEFUNCTION MANIPULATION -------------------------------
    def DVR_to_position_space(self, dvr_state: np.ndarray, x_plot: np.ndarray | None=None) -> np.ndarray:
        """
        Construct the position-space wavefunction from the DVR state
        using interpolation over a range x_plot.
        
        Assumes state is c-normalized.
        
        Parameters
        ----------
        state: np.ndarray
          DVR state. Shape (n_dvr,).
        x_plot: np.ndarray
          Range to interpolate over (len(x_plot)). If None, it defaults to np.linspace(0, L, L*10).
        
        Returns
        -------
        psi: np.ndarray
          Position space wavefunction. Shape (len(x_plot)).
        """
        if x_plot is None:
          x_plot = np.copy(self.x_plot)
        
        # psi = sum_k c_k psi_k
        # psi = sum_j (sum_k U_jk c_k) phi_j
        # psi = sum_j (U @ c)_j phi_j
        j = np.arange(1, self.n+1) # sine mode indices
        k = np.arange(1, self.n+1) # DVR point indices
        
        # build U: shape (n_modes, n_DVRpoints) = (n, n)
        U = sqrt(2.0/(self.n+1)) * sin(pi*np.outer(j, k)/(self.n+1))
        
        # compute a = U @ c (sine coefficients)
        a = U @ dvr_state
        
        # evaluate sin basis on x plot points, shape (len(x_plot), n_modes) = (len(x_plot), n)
        sin_basis = sqrt(2.0/self.L) * sin(pi*np.outer(x_plot, j)/self.L)
        
        psi = sin_basis @ a
        return psi
    
    def position_space_to_DVR(self, rs: np.ndarray, wavefunc: np.ndarray):
        """
        Given a wavefunction psi(r), the DVR coordinate vector,
        c = {c_k}_k, is determined by c_k = omega_k^{1/2} psi(r_k).
        
        Find psi(r_k) through interpolation.
        
        Parameters
        ----------
        rs: np.ndarray
          Radial coordinate values. Shape (len(rs)).
        wavefunc: np.ndarray
          Position space wavefunction. Shape (len(rs)).
        
        Returns
        -------
        c: np.ndarray
          c-normalized DVR state corresponding to wavefunc. Shape (num_dvr).
        """
        # interpolating points r_k and weights omega_k are just DVR mesh
        rs_interpolate = self.r
        omegas = self.w
        
        psi_interp = si.interp1d(rs, wavefunc, kind='cubic')
        c = sqrt(omegas) * psi_interp(rs_interpolate)
        return DVRCore.cnormalize(c)

    # -------------------------------------- UTILITY METHODS -------------------------------------    
    @staticmethod
    def phase_align(state_i: np.ndarray, state_ii: np.ndarray) -> np.ndarray:
        """
        Phase aligns state_ii to state_i with the c-product
        
          ( States can solve eigenproblem and be physically identical but differ by arbitrary 
          phase. this makes things like state_i - state_ii look huge even if the state
          are physically identical. this method removes that phase difference so state_i - state_ii 
          actually measures physical difference. ).
        
        Assumes state_i and state_ii are c-normalized.
        """
        # compute c-product projection
        cprojection = np.sum(state_ii*state_i)
        phase = cprojection / np.abs(cprojection)
        
        # return state_ii w/o the phase
        return state_ii * np.conjugate(phase)
    
    @staticmethod
    def cnormalize(state: np.ndarray) -> np.ndarray:
        """
        c-normalizes a DVR state or a set of DVR states.
        
        Parameters
        ----------
        states: np.ndarray
          DVR states. Shape (num_dvr,) or (num_dvr, num_states).
        
        Returns
        -------
        np.ndarray
          Normalized DVR states. Shape like shape of `states`.
        
        Info
        ----
        If state has shape (num_dvr, num_states). Then,
        the function returns an array of shape (num_dvr, num_states),
        where each column in states has been normalized.
        """
        
        norm = sqrt(np.sum(state**2, axis=0))
        if np.any(np.abs(norm) < 1e-14):
          logger.WARNING("Cannot c-normalize a state with near-zero c-norm.")
        
        return state / norm

class DVR(DVRCore):
  mu, hbar, N = 1/2, 1.0, 2

  def __init__(self,
               n: int,
               L: float,
               rotation_angle: float=0.0,
               potential: Callable[[complex], complex] | None=None,
               l: int=0
            ):
    """
    Constructs a DVR setup for a 1D reduced radial SE with generic 
    radial potential and angular momentum compatible with complex scaling.

    DVR setup uses sine-DVR -> u(0)=0, u(L)=0 BCs.

    Parameters
    ----------
    n : int
        Number of DVR points.
    L : float
        System length.
    rotation_angle: float
        Complex-scaling rotation angle. Default is 0.0.
    potential: Callable[[float], float]
        The radial potential. Default is none.
    l: int
        Angular momentum. Default is 0.
    """
    super().__init__(n, L)
    self.l = l
    self.rotation_angle = rotation_angle
    self.potential = potential

    # construct Hamiltonian
    self.H0 = self.construct_H0(n, L)
    self.V = self.calculate_potential(potential)
    self.H = self.H0 + self.V

  # ------------------------------ CORE DVR SETUP ------------------------------
  def calculate_potential(self, potential: Callable[[complex], complex] | None) -> np.ndarray:
    """
    Computes the matrix form of the complex-scaled potential in the DVR basis (diagonal).
    Includes the centrifugal term.
    """
    
    if self.rotation_angle != 0:
      phase = exp(self.rotation_angle * 1j)
      r = self.r * phase
    else:
      r = self.r
      assert np.all(r > 0)
      
    if potential is None:
        V = 0.0
    else:
        V = np.diag(potential(r))

    l = self.l
    V += np.diag(self.hbar**2/(2*self.mu) * l*(l+1)/r**2)
    return V

  def construct_H0(self, n: int, L: float) -> np.ndarray:
    """
    Computes the matrix form of the free, complex-scaled Hamiltonian in the DVR basis
    """
    T = np.zeros((n, n), dtype=np.complex128)

    for k in range(n):
      for l in range(n):
        kp  = k + 1
        lp = l + 1
        if k == l:
          T[k, l] = (2*(n+1)**2+1)/3 - 1/sin(pi*kp/(n+1))**2
        else:
          T[k, l] = (-1)**(kp-lp) * ( 1/sin(pi*(kp-lp)/(2*(n+1)))**2 - 1/sin(pi*(kp+lp)/(2*(n+1)))**2 )

    coeff = self.hbar**2/(2*self.mu) * pi**2/(2*self.L**2)
    T *= coeff

    if self.rotation_angle != 0:
      phase = exp(-self.rotation_angle * 2j)
      T *= phase

    return T

  def reset_rotation_angle(self, rotation_angle: float):
    """
    Re-computes H0, V, and H with a new rotation angle and refreshes local vars.
    """
    self.rotation_angle = rotation_angle
    self.H0 = self.construct_H0(self.n, self.L)
    self.V = self.calculate_potential(self.potential)
    self.H = self.H0 + self.V

  # ----------------------------- EIGENPAIR COMPUTATIONS -------------------------------------
  def eig(self) -> tuple[np.ndarray, np.ndarray]:
    """
    Computes the ordered eigenpairs for the current Hamiltonian `self.H`.
    Automatically c-normalizes eigenvectors.

    Returns
    -------
    eigvals: np.ndarray
        Ordered (by magnitude) eigenvalues of `self.H`. Shape (self.n).
    eigvecs: np.ndarray
        Eigenvectors of `self.H`, ordered according to eigvals. Shape (self.n, n_eigenvalues=self.n).
    """
        
    eigvals, eigvecs = sl.eig(self.H)
    idx = np.argsort(np.abs(eigvals))
    # order eigenvalues / eigenvectors and c-normalize
    eigvals, eigvecs = eigvals[idx], DVR.cnormalize(eigvecs[:, idx])
    return eigvals, eigvecs

  def closest_eig_pole(self):
    """
    Finds the closest poles of the complex-scaled Hamiltonian at `self.rotation_angle`.
    The finite-volume "scattering states" (finite volume turns the branch cut into a series of poles) 
    are ignored by "nan"-ing any eigenvalue within a certain tolerance (chosen as 0.05 here) to the 
    rotated continuum contour. Thus, this method should ideally return all the resonances (and bound states),
    ordered by their magnitude.
    Automatically c-normalizes eigenvectors.

    Returns
    -------
    eigvals: np.ndarray
        Non-continuum eigenvalues ordered by magnitude. Eigenvalues found to be continuum states
        (within tolerance) at the end of the array with value np.nan. Shape (self.n,).
    eigvecs: np.ndarray
        Eigenvectors ordered according to eigvals. Shape (num_dvr=self.n, self.n)
    """
    eigvals, eigvecs = self.eig()

    contour = np.abs(np.angle(eigvals) - (-2*self.rotation_angle)) < 0.05
    eigvals[contour] = np.nan
    closest_pole_idx = np.argsort(np.abs(eigvals))

    eigvals = eigvals[closest_pole_idx]
    eigvecs = DVR.cnormalize(eigvecs[:, closest_pole_idx])
    return eigvals, eigvecs

  def closest_to_resonance(self, resonance: complex, k=1):
    """
    Finds the k-closest eigenpairs of the complex-scaled Hamiltonian to resonance.
    Automatically c-normalizes eigenvectors.

    Parameters
    ----------
    resonance: complex
        The resonance energy.
    k: int
        Number of closest eigenpairs to compute. Default is 1.

    Returns
    -------
    eigval: np.ndarray
        Eigenvalues ordered by closeness to resonance (in magnitude). Shape (k,).
    eigstate: np.ndarray
        Eigenvectors ordered according to eigval. Shape (n_dvr, k).
    """
    eigvals, eigstates = self.eig()
    idx = np.argsort(np.abs(eigvals - resonance))[:k]
    eigval = eigvals[idx]
    eigstate = DVR.cnormalize(eigstates[:, idx])
    return eigval, eigstate

  # ---------------------------- OBSERVABLE COMPUTATIONS ---------------------------------------
  def compute_rr(self, dvr_state: np.ndarray, rotate_rr: bool=False, regulator: bool=False):
    """
    Computes 1/4 * (r^2) (1/4 factor to account for CM).

    Assumes state is c-normalized.

    Parameters
    ----------
    state: np.ndarray
        DVR state to compute (r^2) from. Shape (self.n,)
    rotate_rr: bool
        Whether to complex-scale the r^2 operator according to `self.rotation_angle`. Default is False.
    regulator: bool
        Whether to regulate off large r with an exponential. Default is False. This has little to no
        use as the only possible states representable with DVR are normalizable, and there's never a need to
        regulate an observable for a normalizable state.

    Returns
    -------
    expect_rr: complex
        The CM-normalized c-product expectation value of r^2.
    """
    # radius is defined as 1/4<r^2> (due to CM)
    # not factoring in the overall $\int d\Omega (Y^0_0)^2$ factor.
    rs = self.r
    if regulator:
        alpha = 0.1
        rs = rs * exp(-alpha * rs)
    if rotate_rr:
        expect_rr = 0.25 * np.sum(dvr_state**2 * rs**2) * exp(2j*self.rotation_angle)
    else:
        expect_rr = 0.25 * np.sum(dvr_state**2 * rs**2)
    return expect_rr

  def compute_density(self, dvr_state: np.ndarray, x_plot: np.ndarray | None=None):
    """
    Computes the density of a DVR state on x_plot, if given.
    Assumes the dvr_state is c-normalized.
    """
    if x_plot is None:
        x_plot = np.copy(self.x_plot)

    wavefunc = self.DVR_to_position_space(dvr_state, x_plot)
    return wavefunc**2
      
  @classmethod
  def compute_transition_mat_element(cls, L, in_state, out_state, rotation_angle, operator="E1"):
      """
      Computes a transition element of the form (out_state | operator | in_state).

      Assumes in_state and out_state are c-normalized.

      Arguments
      ---------
      L : float
          System size.
      in_state : ndarray
          DVR vector corresponding to the incoming state.
      out_state : ndarray
          DVR vector corresponding to the outgoing state.
      rotation_angle : float
          Complex scaling rotation angle.
      operator : str
           A string corresponding to the operator to compute transitions wrt. 
           Default : "E1" corresponding to the EM dipole operator r (no angular factor).

      Output
      ------
      transition_element : complex float
          The transition element.
      """
      n = len(in_state)
      if n != len(out_state):
          raise RuntimeError(f"in_state and out_state can't have different sizes, got len(in_state)={n} and len(out_state)={len(out_state)}")
      r, w = cls.get_mesh(n, L)

      operator_func = getattr(cls, f"_{operator.lower()}", None)
      if operator_func is None:
          raise RuntimeError(f"operator must be a string in self._operator_funcs. Got {operator}.")

      operator_vals = operator_func(rotation_angle, r, w)

      # compute transition element
      transition_element = np.sum(in_state * out_state * operator_vals)
      return transition_element

  # ------------------------------------------------ STATISTICS -------------------------------------
  # most of these stats measure how a complex-scaled wavefunction varies as the rotation angle varies
  @staticmethod
  def c_overlap(states: list[np.ndarray], phis: np.ndarray) -> np.ndarray:
      """ 
      Compute c-product overlap function defined by S(phi) = |1-|(psi_{phi+1} | psi_phi )|^2|.
      
      Assumes all states in `states` are c-normalized to 1. 

      Returns
      -------
      np.ndarray
          Value of c-product overlap between states at each phi. Shape (len(phis)-1,).
      """
      if len(states) != len(phis):
          raise RuntimeError(f"states and phis must have same length. got {len(states)} vs {len(phis)}")
      overlap = []
      for i in range(len(phis)-1):

          # compute c-product projection
          cprojection = np.sum(states[i]*states[i+1])
          # compute overlap via |1 - |projection|^|
          overlap.append(np.abs(1 - np.abs(cprojection)**2))
      return np.array(overlap)

  @staticmethod
  def h_overlap(states: list[np.ndarray], phis: np.ndarray) -> np.ndarray:
      """ 
      Compute h-product overlap function defined by S(phi) = 1-|<psi_{phi+1} | psi_phi >|^2.

      Returns
      -------
      np.ndarray
          Value of Hermitian overlap between states at each phi. Shape (len(phis)-1,).
      """
      if len(states) != len(phis):
          raise RuntimeError(f"states and phis must have same length. got {len(states)} vs {len(phis)}")
          
      overlap = []
      for i in range(len(phis)-1):

          # h-normalize
          statei, stateii = states[i], states[i+1]
          statei = statei / sqrt(np.sum(np.conjugate(statei)*statei))
          stateii = stateii / sqrt(np.sum(np.conjugate(stateii)*stateii))

          # compute h-product projection
          hprojection = np.sum(np.conjugate(stateii)*statei)
          # compute overlap via 1 - |projection|^2
          overlap.append(1 - np.abs(hprojection)**2)
      return np.array(overlap)
    
  @staticmethod
  def phi_deriv_dvr(phis: np.ndarray, states: list[np.ndarray]) -> np.ndarray:
      """
      Compute phi derivative via psi(phi+delta_phi) - psi(phi) / delta_phi (after phase aligning) in DVR.
      
      Assumes all states in `states` are c-normalized to 1.

      Returns
      -------
      np.ndarray
          The value of the derivative in DVR space for each phi. Shape (len(phis)-1, n_dvr).
      """
      # compute derivative with forward difference
      deriv = []
      for i, (state, phi) in enumerate(zip(states[:-1], phis[:-1])):
          next_state = DVRCore.phase_align(state, states[i+1])
          delta_phi = phis[i+1] - phi
          deriv.append((next_state - state) / delta_phi)
      return np.array(deriv)

  def mag_phi_deriv(self, phis: np.ndarray, states: list[np.ndarray], x_plot: np.ndarray | None=None) -> np.ndarray:
      """
      Computes the magnitude of the phi derivative in r-space: |psi(phi+delta_phi)(r) - psi(phi)(r)/ delta_phi| (after phase aligning).
      
      Assumes that x_plot[-1] (self.L if no x_plot given) is large enough that the CS wavefunction is sufficiently zeroed.
      
      Assumes all states in `states` are c-normalized to 1.

      Returns
      -------
      np.ndarray
          The magnitude of the derivative at each r for each phi. Shape (len(phis)-1, len(x_plot)).
      """
      # compute derivative with forward difference
      deriv = []
      for i, (state, phi) in enumerate(zip(states[:-1], phis[:-1])):
          # phase align next state and get delta phi
          next_state = DVRCore.phase_align(state, states[i+1])
          delta_phi = phis[i+1] - phi

          # convert DVR states to position space
          state_rspace = self.DVR_to_position_space(state, x_plot)
          next_state_rspace = self.DVR_to_position_space(next_state, x_plot)
          diff = (next_state_rspace - state_rspace) / delta_phi

          deriv.append(np.abs(diff))
      return np.array(deriv)

  def phi_speed(self, phis: np.ndarray, states: list[np.ndarray], x_plot: np.ndarray | None=None) -> np.ndarray:
      """
      Integrates |phi-derivative| over r for each phi (computes L^2 norm of finite-difference phi-derivative).
      D(phi) = [int dr |psi(phi+delta_phi)-psi(phi)|^2]^{1/2} (after phase aligning).
      This is the path-space speed in phi (speed that functions change in phi) at each phi interval.
      
      Assumes all states in `states` are c-normalized to 1.

      Returns
      -------
      np.ndarray
          Total path difference length at each phi. Shape (len(phis)-1,).
      """

      # assumes that x_plot[-1] (self.L if no x_plot given) is large enough that the CS wavefunction is sufficiently zeroed
      if x_plot is None:
          x_plot = np.copy(self.x_plot)
      dx = x_plot[1] - x_plot[0]
    
      deriv = self.mag_phi_deriv(phis, states, x_plot)
      return sqrt(dx * np.sum(deriv**2, 1))

  def total_phi_path(self, phis: np.ndarray, states: list[np.ndarray], x_plot: np.ndarray | None=None) -> float:
      """
      Computes a total path length in function space as phi varies, integrating over all phi: 
      L = int d phi [int dr |psi(phi+delta_phi)-psi(phi)|^2]^{1/2} (after phase aligning).
      
      Assumes all states in `states` are c-normalized to 1.
      """
      # assumes that x_plot[-1] (self.L if no x_plot given) is large enough that the CS wavefunction is sufficiently zeroed
      dphi = np.diff(phis)

      phi_path_length = self.phi_speed(phis, states, x_plot)
    
      return np.sum(dphi * phi_path_length)

  # -------------------------------- TRANSITION MATRIX ELEMENT OPERATORS -------------------------------
  @staticmethod
  def _e1(rotation_angle: float, r: np.ndarray, w=None):
      """
      Computes the values of the E1 operator at r values
      with rotation angle. w is not used. placed here for
      internal consistency.
      """
      phase = exp(1j*rotation_angle)
      operator = r * phase
      return operator